---
title: "efe3_budget_report_impact_20211207"
author: "Onkar Singh"
date: "12/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
show_in_excel <- function(.data){
  if (interactive()) { # avoid unwanted Excel's executions
    temp <- tempfile(fileext = ".csv") # extension embedded directly
    readr::write_excel_csv(.data, temp) # add BOM for Excel's pleasure
    fs::file_show(temp)
    }
 .data # so that we can continue piping 
}
```


```{r}
budget <- read_csv("efe3_budget_report_impact_20211207.csv") %>% 
  janitor::clean_names()

glimpse(budget)
```
## total budget n actual

```{r}
budget_total_actual <- budget %>% 
  summarize(across(c(original_budget:expenditures_to_date), sum, na.rm = T)) %>% 
  select(original_budget, actual_expenditures ) 
```

## country budgets
```{r}
budget_actual_per_country <- budget %>% 
  group_by(country) %>% 
  summarize(across(c(original_budget:expenditures_to_date), sum, na.rm =T)) %>% 
  select(country, original_budget, actual_expenditures) %>% 
  rowwise() %>% 
  mutate(available_funds = original_budget- actual_expenditures) %>% 
 janitor::adorn_totals() %>% 
  flextable::flextable()

```

## total 

```{r}
budget %>% 
   summarize(total_available_budget = sum (available_budget),
            total_original_budget = sum(original_budget), 
            total_actual_expenditure = sum(actual_expenditures)
            )
```

## year

```{r}
budget %>% 
  group_by(year) %>% 
  summarize(total_available_budget = sum (available_budget),
            total_original_budget = sum(original_budget), 
            total_actual_expenditure = sum(actual_expenditures)
            )
```

## country

```{r}
budget %>% 
  group_by(country) %>% 
  summarize(total_available_budget = sum (available_budget),
            total_original_budget = sum(original_budget), 
            total_actual_expenditure = sum(actual_expenditures)
            )
```

## parent cateogry

```{r}
budget_actual_per_category <-  budget %>% 
  group_by(parent_category) %>% 
  summarize(across(c(original_budget:expenditures_to_date), sum, na.rm =T)) %>% 
  select(parent_category, original_budget, actual_expenditures ) %>%
  rowwise() %>% 
  mutate(available_funds = original_budget- actual_expenditures) %>% 
  filter(available_funds >0) %>% 
  janitor::adorn_totals() 
 
```


## budget parent category and category

```{r}
budget_actual_per_category <-  budget %>% 
  group_by(parent_category, category) %>% 
  summarize(across(c(original_budget:expenditures_to_date), sum, na.rm =T)) %>% 
  select(parent_category, category, original_budget, actual_expenditures ) %>%
  rowwise() %>% 
  mutate(available_funds = original_budget- actual_expenditures) %>% 
  filter(available_funds >0)
```



```{r}
budget %>% 
  group_by(year, country, parent_category) %>% 
  summarize(total_available_budget = sum (available_budget),
            total_original_budget = sum(original_budget), 
            total_actual_expenditure = sum(actual_expenditures)
            )
```

## country year
```{r}
budget %>% 
  group_by(country,  year) %>% 
  summarize(total_available_budget = sum (available_budget),
            total_original_budget = sum(original_budget), 
            total_actual_expenditure = sum(actual_expenditures)
            )
```

